# Generated by Django 5.1 on 2024-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSEI_LMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherdb',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
