# Generated by Django 5.1 on 2024-10-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSEI_LMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationapplication',
            name='agree_terms',
            field=models.BooleanField(default=False, null=True, verbose_name='Agree to Terms'),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='interested_program',
            field=models.CharField(max_length=100, null=True, verbose_name='Interested Program'),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='parent_contact_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Parent Contact Number'),
        ),
        migrations.AddField(
            model_name='accommodationapplication',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='accommodationapplication',
            name='bed_space_option',
            field=models.CharField(choices=[('3_person', '3 Person sharing room bed space and food: 1600AED / month rent'), ('4_person', '4 Person sharing room bed space and food: 1400AED / month rent'), ('5_person', '5 Person sharing room bed space and food: 1500AED / month rent')], max_length=20, verbose_name='Select Bed Space Option'),
        ),
        migrations.AlterField(
            model_name='accommodationapplication',
            name='course_enrolled',
            field=models.CharField(max_length=255, null=True, verbose_name='Course Enrolled'),
        ),
        migrations.AlterField(
            model_name='accommodationapplication',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='accommodationapplication',
            name='start_date_of_accommodation',
            field=models.DateField(null=True, verbose_name='Start Date of Accommodation'),
        ),
        migrations.AlterField(
            model_name='accommodationapplication',
            name='uae_entry_date',
            field=models.DateField(null=True, verbose_name='UAE Entry Date'),
        ),
    ]
