# Generated by Django 5.1 on 2024-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSEI_LMS_App', '0002_alter_coursestudent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
