# Generated by Django 5.1 on 2024-10-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSEI_LMS_App', '0002_accommodationapplication_agree_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationapplication',
            name='course_enrolled',
        ),
    ]
